### PR TITLE
Re-think the logger API and internal propagation between shared core and SDK

### LINKED ISSUE #457: Bring back the function started/function completed log lines
This was removed by mistake in 1.4.0

See https://discord.com/channels/1128210118216007792/1136316066696532069/1301606873035964487

### PR DESCRIPTION
**Pull request by slinkydeveloper**
Fix #457.

This API brings API changes, mostly around naming, to the logger internal api. It also renames a publicly exposed logger interface, now named `LoggerTransport` (reflecting names used in other known JS libraries).

### CODE REVIEW

**Comment by slinkydeveloper** [comment]
This is a final example of the new logs:

```
[restate] [2024-12-10T11:43:51.601Z] INFO:  Listening on 9080...
[restate] [2024-12-10T11:43:51.602Z] WARN:  Accepting requests without validating request signatures; handler access must be restricted
[restate] [2024-12-10T11:43:59.884Z] DEBUG:  Start invocation
[restate] [greeter/greet][inv_17rpyk2iRhDJ2tPathULARLGgJ69lc5nPj][2024-12-10T11:43:59.885Z] INFO:  Starting invocation.
[restate] [greeter/greet][inv_17rpyk2iRhDJ2tPathULARLGgJ69lc5nPj][2024-12-10T11:43:59.889Z] DEBUG:  Executing 'Awakeable'
[restate] [greeter/greet][inv_17rpyk2iRhDJ2tPathULARLGgJ69lc5nPj][2024-12-10T11:43:59.890Z] INFO:  curl -X POST http://localhost:8080/restate/awakeables/prom_1GzI2ITrgrlYBk7BiG3mChq_miA0vBYVRAAAAAQ/resolve --json '"Guardiani"'
[restate] [greeter/greet][inv_17rpyk2iRhDJ2tPathULARLGgJ69lc5nPj][2024-12-10T11:43:59.891Z] DEBUG:  Executing 'Sleep for 1733831049.89s'
[restate] [greeter/greet][inv_17rpyk2iRhDJ2tPathULARLGgJ69lc5nPj][2024-12-10T11:44:09.902Z] WARN:  Invocation completed with an error.
 TimeoutError: Timeout occurred
    at LazyPromise.executor (/home/slinkydeveloper/projects/work/sdk-typescript/packages/restate-sdk/src/context_impl.ts:661:35)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Object.greet (/home/slinkydeveloper/projects/work/sdk-typescript/packages/restate-sdk-examples/src/greeter.ts:26:31)
    at async HandlerWrapper.invoke (/home/slinkydeveloper/projects/work/sdk-typescript/packages/restate-sdk/src/types/rpc.ts:492:26) {
  code: 408,
  [cause]: undefined
}
[restate] [greeter/greet][inv_17rpyk2iRhDJ2tPathULARLGgJ69lc5nPj][2024-12-10T11:44:09.918Z] DEBUG:  Writing invocation result failure value
[restate] [greeter/greet][inv_17rpyk2iRhDJ2tPathULARLGgJ69lc5nPj][2024-12-10T11:44:09.918Z] DEBUG:  End of the invocation
```

The `DEBUG` ones come from the shared core, everything else comes from the SDK

**Comment by slinkydeveloper** [comment]
Improved formatting

```
[restate][2024-12-10T11:49:13.009Z] INFO: Listening on 9080...
[restate][2024-12-10T11:49:13.011Z] WARN: Accepting requests without validating request signatures; handler access must be restricted
[restate][2024-12-10T11:49:18.979Z] DEBUG: Start invocation
[restate][2024-12-10T11:49:18.980Z][greeter/greet][inv_17slXLwGcVIE4J4GswxK5qdBPyRQX63kWZ] INFO: Starting invocation.
[restate][2024-12-10T11:49:18.983Z][greeter/greet][inv_17slXLwGcVIE4J4GswxK5qdBPyRQX63kWZ] DEBUG: Executing 'Awakeable'
[restate][2024-12-10T11:49:18.983Z][greeter/greet][inv_17slXLwGcVIE4J4GswxK5qdBPyRQX63kWZ] INFO: curl -X POST http://localhost:8080/restate/awakeables/prom_1NBzarU8v3FYBk7Bm-eaoZEFBrdrsr1CbAAAAAQ/resolve --json '"Guardiani"'
[restate][2024-12-10T11:49:18.984Z][greeter/greet][inv_17slXLwGcVIE4J4GswxK5qdBPyRQX63kWZ] DEBUG: Executing 'Sleep for 1733831368.984s'
[restate][2024-12-10T11:49:29.002Z][greeter/greet][inv_17slXLwGcVIE4J4GswxK5qdBPyRQX63kWZ] WARN: Invocation completed with an error.
 TimeoutError: Timeout occurred
    at LazyPromise.executor (/home/slinkydeveloper/projects/work/sdk-typescript/packages/restate-sdk/src/context_impl.ts:661:35)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Object.greet (/home/slinkydeveloper/projects/work/sdk-typescript/packages/restate-sdk-examples/src/greeter.ts:26:31)
    at async HandlerWrapper.invoke (/home/slinkydeveloper/projects/work/sdk-typescript/packages/restate-sdk/src/types/rpc.ts:492:26) {
  code: 408,
  [cause]: undefined
}
[restate][2024-12-10T11:49:29.015Z][greeter/greet][inv_17slXLwGcVIE4J4GswxK5qdBPyRQX63kWZ] DEBUG: Writing invocation result failure value
[restate][2024-12-10T11:49:29.016Z][greeter/greet][inv_17slXLwGcVIE4J4GswxK5qdBPyRQX63kWZ] DEBUG: End of the invocation
[restate][2024-12-10T11:49:32.906Z] DEBUG: Start invocation
[restate][2024-12-10T11:49:32.907Z][greeter/greet][inv_16tISe3rmLZ80Bi6SZcG7szC831LLXf3CF] INFO: Starting invocation.
[restate][2024-12-10T11:49:32.907Z][greeter/greet][inv_16tISe3rmLZ80Bi6SZcG7szC831LLXf3CF] DEBUG: Executing 'Awakeable'
[restate][2024-12-10T11:49:32.908Z][greeter/greet][inv_16tISe3rmLZ80Bi6SZcG7szC831LLXf3CF] INFO: curl -X POST http://localhost:8080/restate/awakeables/prom_1qunteHhCeEsBk7BnMGTAMq6qiIJUT8MTAAAAAQ/resolve --json '"Guardiani"'
[restate][2024-12-10T11:49:32.908Z][greeter/greet][inv_16tISe3rmLZ80Bi6SZcG7szC831LLXf3CF] DEBUG: Executing 'Sleep for 1733831382.908s'
[restate][2024-12-10T11:49:42.924Z][greeter/greet][inv_16tISe3rmLZ80Bi6SZcG7szC831LLXf3CF] WARN: Invocation completed with an error.
 TimeoutError: Timeout occurred
    at LazyPromise.executor (/home/slinkydeveloper/projects/work/sdk-typescript/packages/restate-sdk/src/context_impl.ts:661:35)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Object.greet (/home/slinkydeveloper/projects/work/sdk-typescript/packages/restate-sdk-examples/src/greeter.ts:26:31)
    at async HandlerWrapper.invoke (/home/slinkydeveloper/projects/work/sdk-typescript/packages/restate-sdk/src/types/rpc.ts:492:26) {
  code: 408,
  [cause]: undefined
}
[restate][2024-12-10T11:49:42.925Z][greeter/greet][inv_16tISe3rmLZ80Bi6SZcG7szC831LLXf3CF] DEBUG: Writing invocation result failure value
[restate][2024-12-10T11:49:42.925Z][greeter/greet][inv_16tISe3rmLZ80Bi6SZcG7szC831LLXf3CF] DEBUG: End of the invocation
```

**Comment by mupperton** [comment]
Just curious

```
[restate][2024-12-10T11:49:32.908Z][greeter/greet][inv_16tISe3rmLZ80Bi6SZcG7szC831LLXf3CF] INFO: curl -X POST http://localhost:8080/restate/awakeables/prom_1qunteHhCeEsBk7BnMGTAMq6qiIJUT8MTAAAAAQ/resolve --json '"Guardiani"'
```

This appears to be showing the resolving of an awakeable and the value it is being resolved with?

What else is going to be shown this way? Like, ctx.serviceClient calls and their payload?

Can there be a way to opt-out of exposing the values/payloads in logs if they could be sensitive?

**Comment by slinkydeveloper** [comment]
> This appears to be showing the resolving of an awakeable and the value it is being resolved with?
What else is going to be shown this way? Like, ctx.serviceClient calls and their payload?
Can there be a way to opt-out of exposing the values/payloads in logs if they could be sensitive?

This is not from the SDK, this is a manual console log statement in the code: https://github.com/restatedev/sdk-typescript/blob/main/packages/restate-sdk-examples/src/greeter.ts#L20

**Comment by mupperton** [comment]
> This is not from the SDK, this is a manual console log statement in the code: https://github.com/restatedev/sdk-typescript/blob/main/packages/restate-sdk-examples/src/greeter.ts#L20

Ahh! All good then

So what's this about:
```
DEBUG: Executing 'Sleep for 1733831382.908s'
```
That's like 55 years lol

**Comment by slinkydeveloper** [comment]
This one is now ready to merge, pending re-generating the VM and fixing the conflict

**Pull request merged**
